### ISSUE TITLE
NaN

### ISSUE THREAD

**Issue by electic** [dsfields/elv#1]
Great package! Thank you for putting out there. I have one question, shouldn't it also catch NaN?

**Comment by dsfields** [comment]
Hmmmm...perhaps.  The module was originally intended to answer the question of whether or not something was defined.  Does NaN qualify as "defined"?  What do you say to a property on `elv` that allows you to define behavior.  Something like this:

```
const elv = require('elv');
console.log(elv.behavior.isUndefined); // true
console.log(elv.behavior.isNull); // true
elv.behavior.isNaN = true; // default is false
```

Here, we can turn on and off elv's various existential checks.

**Comment by electic** [comment]
I think that would be awesome.

**Comment by dsfields** [comment]
This work has been published to NPM.  Cheers.

**Comment by electic** [comment]
Thank you!
